name: Conviso AST
on:
 workflow_dispatch:
 push:
   branches: [ master, staging ]
jobs:
  conviso-ast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Running Conviso AST
        uses: convisoappsec/conviso-ast@main
        env:
          CONVISO_API_KEY: '${{ secrets.CONVISO_API_KEY }}'
